exports.mangobilling = {
  MANGO_CREATE_CLIENT:
    "https://secure.mangobilling.com/api/vendor/createMangoClient",
  MANGO_UPDATE_CLIENT:
    "https://secure.mangobilling.com/api/vendor/updateMangoClient/:mangoClientID",
  MANGO_DELETE_CLIENT:
    "https://secure.mangobilling.com/api/vendor/deleteMangoClient/:mangoClientID",
  MANGO_CREATE_FOLDER:
    "https://secure.mangobilling.com/api/vendor/createMangoFolder",
  MANGO_UPDATE_FOLDER:
    "https://secure.mangobilling.com/api/vendor/updateMangoFolder",
  MANGO_DELETE_FOLDER:
    "https://secure.mangobilling.com/api/vendor/deleteFilesFolders/:clientId/:companyId",
  MANGO_CREATE_FILE: "https://secure.mangobilling.com/api/vendor/uploadfile",
  MANGO_UPDATE_FILE:
    "https://secure.mangobilling.com/api/vendor/updateMangoFolder",
  MANGO_ARCHIVE_FILE:
    "https://secure.mangobilling.com/api/vendor/archiveFilesFolders/:clientId/:companyId",
  MANGO_DELETE_FILE:
    "https://secure.mangobilling.com/api/vendor/deleteFilesFolders/:clientId/:companyId",
};

exports.staxConstants = {
  STAX_plan: "mangobilling",
  STAX_brand: "mangobilling-sandbox",
  STAX_PAY_KEY: "Mango-Billing-Payments-Testing-b4b0887e1dc7",
  STAX_API: "https://apiprod.fattlabs.com",
  STAX_REDIRECT_URL: "https://signup.fattmerchant.com/#/sso?",
  STAX_API_ENROLLMENT_KEY:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnb2RVc2VyIjp0cnVlLCJtZXJjaGFudCI6IjVhZGI4Yzc4LWQ1ZTUtNGU5OC04N2RkLWY1OTkyNjgzNjMyOCIsInN1YiI6Ijk2NGFmOGM4LTI3MTctNGNlYS04ZTMxLWZkZWIyNTYyMWFjMCIsImJyYW5kIjoibWFuZ29iaWxsaW5nLXNhbmRib3giLCJpc3MiOiJodHRwOi8vYXBpcHJvZC5mYXR0bGFicy5jb20vdXNlci85NjRhZjhjOC0yNzE3LTRjZWEtOGUzMS1mZGViMjU2MjFhYzAiLCJpYXQiOjE2MTY1Mzg2NzUsImV4cCI6NDc3MDEzODY3NSwibmJmIjoxNjE2NTM4Njc1LCJqdGkiOiJKUTI1UVR5YzNoSUkxMHp1IiwiYXNzdW1pbmciOmZhbHNlfQ._RXZRQkB-970Qr26a9vakCwM3QZrs6tdd7WUnpYO_5Q",
  STAX_API_PAYMENT_KEY:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnb2RVc2VyIjpmYWxzZSwibWVyY2hhbnQiOiJmOTEwN2QwMi0zYTEwLTQ5ZWQtYjA3Ni03MjIzMmQwZDhmZDEiLCJzdWIiOiJmNjUxOTg5NC1jYjVkLTRjOWItOTMwYi02YmMwMTdjMzFjYzYiLCJicmFuZCI6Im1hbmdvYmlsbGluZy1zYW5kYm94IiwiaXNzIjoiaHR0cDovL2FwaXByb2QuZmF0dGxhYnMuY29tL3VzZXIiLCJpYXQiOjE2MTY1Mzc0MDYsImV4cCI6NDc3MDEzNzQwNiwibmJmIjoxNjE2NTM3NDA2LCJqdGkiOiJlV29XS0ZyRHJPaGo2djVIIiwiYXNzdW1pbmciOmZhbHNlfQ.dRJ3p4938SEMIaMvmVFFFyR_0491jKK6UBdvAWiGbyI",
};

exports.domain = {
  DEMO_URL: 'https://demo.imaginetime.com',
  LOCAL_URL: 'http://localhost:3030',
}

exports.COUNTRIES = {
  US: { name: 'United States', code: 'US' },
  CA: { name: 'Canada', code: 'CA' },
  AF: { name: 'Afghanistan', code: 'AF' },
  AX: { name: 'Åland Islands', code: 'AX' },
  AL: { name: 'Albania', code: 'AL' },
  DZ: { name: 'Algeria', code: 'DZ' },
  AS: { name: 'American Samoa', code: 'AS' },
  AD: { name: 'AndorrA', code: 'AD' },
  AO: { name: 'Angola', code: 'AO' },
  AI: { name: 'Anguilla', code: 'AI' },
  AQ: { name: 'Antarctica', code: 'AQ' },
  AG: { name: 'Antigua and Barbuda', code: 'AG' },
  AR: { name: 'Argentina', code: 'AR' },
  AM: { name: 'Armenia', code: 'AM' },
  AW: { name: 'Aruba', code: 'AW' },
  AU: { name: 'Australia', code: 'AU' },
  AT: { name: 'Austria', code: 'AT' },
  AZ: { name: 'Azerbaijan', code: 'AZ' },
  BS: { name: 'Bahamas', code: 'BS' },
  BH: { name: 'Bahrain', code: 'BH' },
  BD: { name: 'Bangladesh', code: 'BD' },
  BB: { name: 'Barbados', code: 'BB' },
  BY: { name: 'Belarus', code: 'BY' },
  BE: { name: 'Belgium', code: 'BE' },
  BZ: { name: 'Belize', code: 'BZ' },
  BJ: { name: 'Benin', code: 'BJ' },
  BM: { name: 'Bermuda', code: 'BM' },
  BT: { name: 'Bhutan', code: 'BT' },
  BO: { name: 'Bolivia', code: 'BO' },
  BA: { name: 'Bosnia and Herzegovina', code: 'BA' },
  BW: { name: 'Botswana', code: 'BW' },
  BV: { name: 'Bouvet Island', code: 'BV' },
  BR: { name: 'Brazil', code: 'BR' },
  IO: { name: 'British Indian Ocean Territory', code: 'IO' },
  BN: { name: 'Brunei Darussalam', code: 'BN' },
  BG: { name: 'Bulgaria', code: 'BG' },
  BF: { name: 'Burkina Faso', code: 'BF' },
  BI: { name: 'Burundi', code: 'BI' },
  KH: { name: 'Cambodia', code: 'KH' },
  CM: { name: 'Cameroon', code: 'CM' },
  CV: { name: 'Cape Verde', code: 'CV' },
  KY: { name: 'Cayman Islands', code: 'KY' },
  CF: { name: 'Central African Republic', code: 'CF' },
  TD: { name: 'Chad', code: 'TD' },
  CL: { name: 'Chile', code: 'CL' },
  CN: { name: 'China', code: 'CN' },
  CX: { name: 'Christmas Island', code: 'CX' },
  CC: { name: 'Cocos (Keeling) Islands', code: 'CC' },
  CO: { name: 'Colombia', code: 'CO' },
  KM: { name: 'Comoros', code: 'KM' },
  CG: { name: 'Congo', code: 'CG' },
  CD: { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  CK: { name: 'Cook Islands', code: 'CK' },
  CR: { name: 'Costa Rica', code: 'CR' },
  CI: { name: "Cote D'Ivoire", code: 'CI' },
  HR: { name: 'Croatia', code: 'HR' },
  CU: { name: 'Cuba', code: 'CU' },
  CY: { name: 'Cyprus', code: 'CY' },
  CZ: { name: 'Czech Republic', code: 'CZ' },
  DK: { name: 'Denmark', code: 'DK' },
  DJ: { name: 'Djibouti', code: 'DJ' },
  DM: { name: 'Dominica', code: 'DM' },
  DO: { name: 'Dominican Republic', code: 'DO' },
  EC: { name: 'Ecuador', code: 'EC' },
  EG: { name: 'Egypt', code: 'EG' },
  SV: { name: 'El Salvador', code: 'SV' },
  GQ: { name: 'Equatorial Guinea', code: 'GQ' },
  ER: { name: 'Eritrea', code: 'ER' },
  EE: { name: 'Estonia', code: 'EE' },
  ET: { name: 'Ethiopia', code: 'ET' },
  FK: { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  FO: { name: 'Faroe Islands', code: 'FO' },
  FJ: { name: 'Fiji', code: 'FJ' },
  FI: { name: 'Finland', code: 'FI' },
  FR: { name: 'France', code: 'FR' },
  GF: { name: 'French Guiana', code: 'GF' },
  PF: { name: 'French Polynesia', code: 'PF' },
  TF: { name: 'French Southern Territories', code: 'TF' },
  GA: { name: 'Gabon', code: 'GA' },
  GM: { name: 'Gambia', code: 'GM' },
  GE: { name: 'Georgia', code: 'GE' },
  DE: { name: 'Germany', code: 'DE' },
  GH: { name: 'Ghana', code: 'GH' },
  GI: { name: 'Gibraltar', code: 'GI' },
  GR: { name: 'Greece', code: 'GR' },
  GL: { name: 'Greenland', code: 'GL' },
  GD: { name: 'Grenada', code: 'GD' },
  GP: { name: 'Guadeloupe', code: 'GP' },
  GU: { name: 'Guam', code: 'GU' },
  GT: { name: 'Guatemala', code: 'GT' },
  GG: { name: 'Guernsey', code: 'GG' },
  GN: { name: 'Guinea', code: 'GN' },
  GW: { name: 'Guinea-Bissau', code: 'GW' },
  GY: { name: 'Guyana', code: 'GY' },
  HT: { name: 'Haiti', code: 'HT' },
  HM: { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  VA: { name: 'Holy See (Vatican City State)', code: 'VA' },
  HN: { name: 'Honduras', code: 'HN' },
  HK: { name: 'Hong Kong', code: 'HK' },
  HU: { name: 'Hungary', code: 'HU' },
  IS: { name: 'Iceland', code: 'IS' },
  IN: { name: 'India', code: 'IN' },
  ID: { name: 'Indonesia', code: 'ID' },
  IR: { name: 'Iran, Islamic Republic Of', code: 'IR' },
  IQ: { name: 'Iraq', code: 'IQ' },
  IE: { name: 'Ireland', code: 'IE' },
  IM: { name: 'Isle of Man', code: 'IM' },
  IL: { name: 'Israel', code: 'IL' },
  IT: { name: 'Italy', code: 'IT' },
  JM: { name: 'Jamaica', code: 'JM' },
  JP: { name: 'Japan', code: 'JP' },
  JE: { name: 'Jersey', code: 'JE' },
  JO: { name: 'Jordan', code: 'JO' },
  KZ: { name: 'Kazakhstan', code: 'KZ' },
  KE: { name: 'Kenya', code: 'KE' },
  KI: { name: 'Kiribati', code: 'KI' },
  KP: { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  KR: { name: 'Korea, Republic of', code: 'KR' },
  KW: { name: 'Kuwait', code: 'KW' },
  KG: { name: 'Kyrgyzstan', code: 'KG' },
  LA: { name: "Lao People'S Democratic Republic", code: 'LA' },
  LV: { name: 'Latvia', code: 'LV' },
  LB: { name: 'Lebanon', code: 'LB' },
  LS: { name: 'Lesotho', code: 'LS' },
  LR: { name: 'Liberia', code: 'LR' },
  LY: { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  LI: { name: 'Liechtenstein', code: 'LI' },
  LT: { name: 'Lithuania', code: 'LT' },
  LU: { name: 'Luxembourg', code: 'LU' },
  MO: { name: 'Macao', code: 'MO' },
  MK: { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  MG: { name: 'Madagascar', code: 'MG' },
  MW: { name: 'Malawi', code: 'MW' },
  MY: { name: 'Malaysia', code: 'MY' },
  MV: { name: 'Maldives', code: 'MV' },
  ML: { name: 'Mali', code: 'ML' },
  MT: { name: 'Malta', code: 'MT' },
  MH: { name: 'Marshall Islands', code: 'MH' },
  MQ: { name: 'Martinique', code: 'MQ' },
  MR: { name: 'Mauritania', code: 'MR' },
  MU: { name: 'Mauritius', code: 'MU' },
  YT: { name: 'Mayotte', code: 'YT' },
  MX: { name: 'Mexico', code: 'MX' },
  FM: { name: 'Micronesia, Federated States of', code: 'FM' },
  MD: { name: 'Moldova, Republic of', code: 'MD' },
  MC: { name: 'Monaco', code: 'MC' },
  MN: { name: 'Mongolia', code: 'MN' },
  MS: { name: 'Montserrat', code: 'MS' },
  MA: { name: 'Morocco', code: 'MA' },
  MZ: { name: 'Mozambique', code: 'MZ' },
  MM: { name: 'Myanmar', code: 'MM' },
  NA: { name: 'Namibia', code: 'NA' },
  NR: { name: 'Nauru', code: 'NR' },
  NP: { name: 'Nepal', code: 'NP' },
  NL: { name: 'Netherlands', code: 'NL' },
  AN: { name: 'Netherlands Antilles', code: 'AN' },
  NC: { name: 'New Caledonia', code: 'NC' },
  NZ: { name: 'New Zealand', code: 'NZ' },
  NI: { name: 'Nicaragua', code: 'NI' },
  NE: { name: 'Niger', code: 'NE' },
  NG: { name: 'Nigeria', code: 'NG' },
  NU: { name: 'Niue', code: 'NU' },
  NF: { name: 'Norfolk Island', code: 'NF' },
  MP: { name: 'Northern Mariana Islands', code: 'MP' },
  NO: { name: 'Norway', code: 'NO' },
  OM: { name: 'Oman', code: 'OM' },
  PK: { name: 'Pakistan', code: 'PK' },
  PW: { name: 'Palau', code: 'PW' },
  PS: { name: 'Palestinian Territory, Occupied', code: 'PS' },
  PA: { name: 'Panama', code: 'PA' },
  PG: { name: 'Papua New Guinea', code: 'PG' },
  PY: { name: 'Paraguay', code: 'PY' },
  PE: { name: 'Peru', code: 'PE' },
  PH: { name: 'Philippines', code: 'PH' },
  PN: { name: 'Pitcairn', code: 'PN' },
  PL: { name: 'Poland', code: 'PL' },
  PT: { name: 'Portugal', code: 'PT' },
  PR: { name: 'Puerto Rico', code: 'PR' },
  QA: { name: 'Qatar', code: 'QA' },
  RE: { name: 'Reunion', code: 'RE' },
  RO: { name: 'Romania', code: 'RO' },
  RU: { name: 'Russian Federation', code: 'RU' },
  RW: { name: 'RWANDA', code: 'RW' },
  SH: { name: 'Saint Helena', code: 'SH' },
  KN: { name: 'Saint Kitts and Nevis', code: 'KN' },
  LC: { name: 'Saint Lucia', code: 'LC' },
  PM: { name: 'Saint Pierre and Miquelon', code: 'PM' },
  VC: { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  WS: { name: 'Samoa', code: 'WS' },
  SM: { name: 'San Marino', code: 'SM' },
  ST: { name: 'Sao Tome and Principe', code: 'ST' },
  SA: { name: 'Saudi Arabia', code: 'SA' },
  SN: { name: 'Senegal', code: 'SN' },
  CS: { name: 'Serbia and Montenegro', code: 'CS' },
  SC: { name: 'Seychelles', code: 'SC' },
  SL: { name: 'Sierra Leone', code: 'SL' },
  SG: { name: 'Singapore', code: 'SG' },
  SK: { name: 'Slovakia', code: 'SK' },
  SI: { name: 'Slovenia', code: 'SI' },
  SB: { name: 'Solomon Islands', code: 'SB' },
  SO: { name: 'Somalia', code: 'SO' },
  ZA: { name: 'South Africa', code: 'ZA' },
  GS: { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  ES: { name: 'Spain', code: 'ES' },
  LK: { name: 'Sri Lanka', code: 'LK' },
  SD: { name: 'Sudan', code: 'SD' },
  SR: { name: 'Suriname', code: 'SR' },
  SJ: { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  SZ: { name: 'Swaziland', code: 'SZ' },
  SE: { name: 'Sweden', code: 'SE' },
  CH: { name: 'Switzerland', code: 'CH' },
  SY: { name: 'Syrian Arab Republic', code: 'SY' },
  TW: { name: 'Taiwan, Province of China', code: 'TW' },
  TJ: { name: 'Tajikistan', code: 'TJ' },
  TZ: { name: 'Tanzania, United Republic of', code: 'TZ' },
  TH: { name: 'Thailand', code: 'TH' },
  TL: { name: 'Timor-Leste', code: 'TL' },
  TG: { name: 'Togo', code: 'TG' },
  TK: { name: 'Tokelau', code: 'TK' },
  TO: { name: 'Tonga', code: 'TO' },
  TT: { name: 'Trinidad and Tobago', code: 'TT' },
  TN: { name: 'Tunisia', code: 'TN' },
  TR: { name: 'Turkey', code: 'TR' },
  TM: { name: 'Turkmenistan', code: 'TM' },
  TC: { name: 'Turks and Caicos Islands', code: 'TC' },
  TV: { name: 'Tuvalu', code: 'TV' },
  UG: { name: 'Uganda', code: 'UG' },
  UA: { name: 'Ukraine', code: 'UA' },
  AE: { name: 'United Arab Emirates', code: 'AE' },
  GB: { name: 'United Kingdom', code: 'GB' },
  UM: { name: 'United States Minor Outlying Islands', code: 'UM' },
  UY: { name: 'Uruguay', code: 'UY' },
  UZ: { name: 'Uzbekistan', code: 'UZ' },
  VU: { name: 'Vanuatu', code: 'VU' },
  VE: { name: 'Venezuela', code: 'VE' },
  VN: { name: 'Viet Nam', code: 'VN' },
  VG: { name: 'Virgin Islands, British', code: 'VG' },
  VI: { name: 'Virgin Islands, U.S.', code: 'VI' },
  WF: { name: 'Wallis and Futuna', code: 'WF' },
  EH: { name: 'Western Sahara', code: 'EH' },
  YE: { name: 'Yemen', code: 'YE' },
  ZM: { name: 'Zambia', code: 'ZM' },
  ZW: { name: 'Zimbabwe', code: 'ZW' }
}

exports.STATES = {
  AL: { name: 'Alabama', code: 'AL' },
  AK: { name: 'Alaska', code: 'AK' },
  AS: { name: 'American Samoa', code: 'AS' },
  AZ: { name: 'Arizona', code: 'AZ' },
  AR: { name: 'Arkansas', code: 'AR' },
  CA: { name: 'California', code: 'CA' },
  CO: { name: 'Colorado', code: 'CO' },
  CT: { name: 'Connecticut', code: 'CT' },
  DE: { name: 'Delaware', code: 'DE' },
  DC: { name: 'District Of Columbia', code: 'DC' },
  FM: { name: 'Federated States Of Micronesia', code: 'FM' },
  FL: { name: 'Florida', code: 'FL' },
  GA: { name: 'Georgia', code: 'GA' },
  GU: { name: 'Guam', code: 'GU' },
  HI: { name: 'Hawaii', code: 'HI' },
  ID: { name: 'Idaho', code: 'ID' },
  IL: { name: 'Illinois', code: 'IL' },
  IN: { name: 'Indiana', code: 'IN' },
  IA: { name: 'Iowa', code: 'IA' },
  KS: { name: 'Kansas', code: 'KS' },
  KY: { name: 'Kentucky', code: 'KY' },
  LA: { name: 'Louisiana', code: 'LA' },
  ME: { name: 'Maine', code: 'ME' },
  MH: { name: 'Marshall Islands', code: 'MH' },
  MD: { name: 'Maryland', code: 'MD' },
  MA: { name: 'Massachusetts', code: 'MA' },
  MI: { name: 'Michigan', code: 'MI' },
  MN: { name: 'Minnesota', code: 'MN' },
  MS: { name: 'Mississippi', code: 'MS' },
  MO: { name: 'Missouri', code: 'MO' },
  MT: { name: 'Montana', code: 'MT' },
  NE: { name: 'Nebraska', code: 'NE' },
  NV: { name: 'Nevada', code: 'NV' },
  NH: { name: 'New Hampshire', code: 'NH' },
  NJ: { name: 'New Jersey', code: 'NJ' },
  NM: { name: 'New Mexico', code: 'NM' },
  NY: { name: 'New York', code: 'NY' },
  NC: { name: 'North Carolina', code: 'NC' },
  ND: { name: 'North Dakota', code: 'ND' },
  MP: { name: 'Northern Mariana Islands', code: 'MP' },
  OH: { name: 'Ohio', code: 'OH' },
  OK: { name: 'Oklahoma', code: 'OK' },
  OR: { name: 'Oregon', code: 'OR' },
  PW: { name: 'Palau', code: 'PW' },
  PA: { name: 'Pennsylvania', code: 'PA' },
  PR: { name: 'Puerto Rico', code: 'PR' },
  RI: { name: 'Rhode Island', code: 'RI' },
  SC: { name: 'South Carolina', code: 'SC' },
  SD: { name: 'South Dakota', code: 'SD' },
  TN: { name: 'Tennessee', code: 'TN' },
  TX: { name: 'Texas', code: 'TX' },
  UT: { name: 'Utah', code: 'UT' },
  VT: { name: 'Vermont', code: 'VT' },
  VI: { name: 'Virgin Islands', code: 'VI' },
  VA: { name: 'Virginia', code: 'VA' },
  WA: { name: 'Washington', code: 'WA' },
  WV: { name: 'West Virginia', code: 'WV' },
  WI: { name: 'Wisconsin', code: 'WI' },
  WY: { name: 'Wyoming', code: 'WY' }
}

exports.COUNTRY_STATES = {
  "US": {
    AL: { name: 'Alabama', code: 'AL' },
    AK: { name: 'Alaska', code: 'AK' },
    AS: { name: 'American Samoa', code: 'AS' },
    AZ: { name: 'Arizona', code: 'AZ' },
    AR: { name: 'Arkansas', code: 'AR' },
    CA: { name: 'California', code: 'CA' },
    CO: { name: 'Colorado', code: 'CO' },
    CT: { name: 'Connecticut', code: 'CT' },
    DE: { name: 'Delaware', code: 'DE' },
    DC: { name: 'District Of Columbia', code: 'DC' },
    FM: { name: 'Federated States Of Micronesia', code: 'FM' },
    FL: { name: 'Florida', code: 'FL' },
    GA: { name: 'Georgia', code: 'GA' },
    GU: { name: 'Guam', code: 'GU' },
    HI: { name: 'Hawaii', code: 'HI' },
    ID: { name: 'Idaho', code: 'ID' },
    IL: { name: 'Illinois', code: 'IL' },
    IN: { name: 'Indiana', code: 'IN' },
    IA: { name: 'Iowa', code: 'IA' },
    KS: { name: 'Kansas', code: 'KS' },
    KY: { name: 'Kentucky', code: 'KY' },
    LA: { name: 'Louisiana', code: 'LA' },
    ME: { name: 'Maine', code: 'ME' },
    MH: { name: 'Marshall Islands', code: 'MH' },
    MD: { name: 'Maryland', code: 'MD' },
    MA: { name: 'Massachusetts', code: 'MA' },
    MI: { name: 'Michigan', code: 'MI' },
    MN: { name: 'Minnesota', code: 'MN' },
    MS: { name: 'Mississippi', code: 'MS' },
    MO: { name: 'Missouri', code: 'MO' },
    MT: { name: 'Montana', code: 'MT' },
    NE: { name: 'Nebraska', code: 'NE' },
    NV: { name: 'Nevada', code: 'NV' },
    NH: { name: 'New Hampshire', code: 'NH' },
    NJ: { name: 'New Jersey', code: 'NJ' },
    NM: { name: 'New Mexico', code: 'NM' },
    NY: { name: 'New York', code: 'NY' },
    NC: { name: 'North Carolina', code: 'NC' },
    ND: { name: 'North Dakota', code: 'ND' },
    MP: { name: 'Northern Mariana Islands', code: 'MP' },
    OH: { name: 'Ohio', code: 'OH' },
    OK: { name: 'Oklahoma', code: 'OK' },
    OR: { name: 'Oregon', code: 'OR' },
    PW: { name: 'Palau', code: 'PW' },
    PA: { name: 'Pennsylvania', code: 'PA' },
    PR: { name: 'Puerto Rico', code: 'PR' },
    RI: { name: 'Rhode Island', code: 'RI' },
    SC: { name: 'South Carolina', code: 'SC' },
    SD: { name: 'South Dakota', code: 'SD' },
    TN: { name: 'Tennessee', code: 'TN' },
    TX: { name: 'Texas', code: 'TX' },
    UT: { name: 'Utah', code: 'UT' },
    VT: { name: 'Vermont', code: 'VT' },
    VI: { name: 'Virgin Islands', code: 'VI' },
    VA: { name: 'Virginia', code: 'VA' },
    WA: { name: 'Washington', code: 'WA' },
    WV: { name: 'West Virginia', code: 'WV' },
    WI: { name: 'Wisconsin', code: 'WI' },
    WY: { name: 'Wyoming', code: 'WY' }
  }
  , "CA": {
    AB: { name: 'Alberta', code: 'AB' },
    BC: { name: 'British Columbia', code: 'BC' },
    MB: { name: 'Manitoba', code: 'MB' },
    NB: { name: 'New Brunswick', code: 'NB' },
    NL: { name: 'Newfoundland and Labrador', code: 'NL' },
    NT: { name: 'Northwest Territories', code: 'NT' },
    NS: { name: 'Nova Scotia', code: 'NS' },
    NU: { name: 'Nunavut', code: 'NU' },
    ON: { name: 'Ontario', code: 'ON' },
    PE: { name: 'Prince Edward Island', code: 'PE' },
    QC: { name: 'Quebec', code: 'QC' },
    SK: { name: 'Saskatchewan', code: 'SK' },
    YT: { name: 'Yukon Territory', code: 'YT' }
  }
};

exports.FOLDER_PERMISSION_FIELDS = [
  'adminRead'
  ,'adminCreate'
  ,'adminUpdate'
  ,'adminDelete'
  ,'adminDownload'
  ,'adminUpload'
  ,'ownerRead'
  ,'ownerCreate'
  ,'ownerUpdate'
  ,'ownerDelete'
  ,'ownerDownload'
  ,'ownerUpload'
  ,'staffRead'
  ,'staffCreate'
  ,'staffUpdate'
  ,'staffDelete'
  ,'staffDownload'
  ,'staffUpload'
  ,'contactRead'
  ,'contactCreate'
  ,'contactUpdate'
  ,'contactDelete'
  ,'contactDownload'
  ,'contactUpload'
  ,'showFolderClientPortal'
]

exports.jsBundleScripts = {
  "development": [
    "/js/vendor.js",
    "/js/react-bundle.js"
  ]
  , "stagingdemo": [
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/stagingdemo/vendor.js" ,
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/stagingdemo/react-bundle.js"
  ]
  , "demo": [
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/demo/vendor.js" ,
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/demo/react-bundle.js"
  ]
  , "demo2": [
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/demo2/vendor.js" ,
    "https://storage.googleapis.com/it-fugi-demo/react-bundle/demo2/react-bundle.js"
  ]
  , "testproduction": [
    // "https://storage.googleapis.com/it-fugi-prod/react-bundle/testproduction/vendor.js" ,
    "https://storage.googleapis.com/it-fugi-prod/react-bundle/testproduction/react-bundle.js"
  ]
  , "production": [
    //"https://storage.googleapis.com/it-fugi-prod/react-bundle/production/vendor.js" ,
    "https://storage.googleapis.com/it-fugi-prod/react-bundle/production/react-bundle.js"
  ]
  , "production2": [
    //"https://storage.googleapis.com/it-fugi-prod/react-bundle/production2/vendor.js",
    "https://storage.googleapis.com/it-fugi-prod/react-bundle/production2/react-bundle.js"
  ]

}

